spring:
  data:
    mongodb:
      host: mongo
      username: ${MONGODB_USER}
      password: ${MONGODB_PASSWORD}
      database: ${MONGODB_DATABASE}
      port: 27017

logging.level.org.springframework.security.oauth2: DEBUG