swagger: '2.0'
info:
  title: Test API
  description: Test restful api
  version: 1.0.0
host: localhost:8090
schemes:
- https
- http
basePath: /
produces:
- application/json
paths:
  /item/price:
    post:
      parameters:
      - name: requestJson
        in: body
        description: The request item JSON you want to post
        schema:
          $ref: '#/definitions/QueryPriceRequest'
        required: true
      responses:
        200:
          description: success response
          schema:
            $ref: '#/definitions/QueryPriceResponse'
definitions:
  QueryItem:
    type: object
    properties:
      productId:
        type: string
      skuId:
        type: string
      quantity:
        type: integer
  PriceItem:
    type: object
    description: Price info
    properties:
      productId:
        type: string
        description: The product Id of product
      skuId:
        type: string
        description: The sku Id
      price:
        type: string
        format: double
        description: item price
      quantity:
        type: integer
        description: item quantity
      totalPrice:
        type: string
        format: double
        description: item total price
      priceSchema:
        type: string
        description: earlybird price, standard price or onsite price
      message:
        type: string
        description: The discount message
  QueryPriceResponse:
    type: object
    properties:
      itemPrices:
        type: array
        items:
          $ref: '#/definitions/PriceItem'
  QueryPriceRequest:
    type: object
    properties:
      showId:
        type: string
      userId:
        type: string
      locale:
        type: string
      items:
        type: array
        items:
          $ref: '#/definitions/QueryItem'