management.context-path: /mgmt

from: config

spring.boot.admin.url: http://manage:7100
spring.boot.admin.client.name: "${spring.application.name}-${stack.service:default}"

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
#  rabbitmq:
#    host: rabbitmq

logging:
  level:
    org.springframework.security: INFO
